---
type: docker
kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
        from_secret: DOCKERHUB_USER
    password:
      from_secret: DOCKERHUB_PASS
    repo:
      from_secret: DOCKERHUB_REPOSITORY
    tags:
    - latest